name: PR Title Check

on:
  pull_request:
    types: [opened] # Correction ici
    branches:
      - main

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Validate PR title
        run: |
          if [[ ! "$(echo '${{ github.event.pull_request.title }}' | grep -E '^\[(BUGFIX|MINORFEATURE|MAJORFEATURE)\]')" ]]; then
            echo "Error: Pull request title must start with [BUGFIX], [MINORFEATURE], or [MAJORFEATURE]."
            exit 1
          fi
